### ISSUE TITLE
Ale linter

### ISSUE THREAD

**Issue by john-kurkowski** [ElmCast/elm-vim#102]
elm-vim supports Syntastic out of the box but you might want to divert that effort to [Ale](https://github.com/w0rp/ale) instead. Ale is the new hotness for linting in Vim. It takes advantage of Vim 8's async tasks. Ale's UX and speed leave Syntastic in the dust. Syntastic's architecture [may not recover](https://github.com/w0rp/ale/issues/16).

Ale collects all language linters in its repo. So this isn't a request for elm-vim's repo. Rather it's for interested people here, those familiar with Elm tooling, to contribute to Ale's repo.

**Comment by BuffaloCoder** [comment]
Turns out this wasn't too difficult. The only problem is that to use elm-make properly the directory needs to be set to the project root. This is done in elm-vim by calling s:ExecuteInRoot, which calls the command after changing the directory to path returned from s:FindRootDirectory. This can be solved in ale by using the path from s:FindRootDirectory when creating the command string, and changing the directory to it before calling the elm-make command.

Knowing this, I made a [fork](https://github.com/BuffaloCoder/ale) that handles Elm linting; the linter file can be found [here](https://github.com/BuffaloCoder/ale/blob/master/ale_linters/elm/make.vim).

@ajhager - Since I'm copying that s:FindRootDirectory wholesale, should there be any additional attributions in the source for this project? (I'm not that familiar with the BSD-3 License)

**Comment by ajhager** [comment]
This looks great. I hereby give you permission to use that function for whatever purpose you need. :)

**Comment by BuffaloCoder** [comment]
Thanks! XD

**Comment by BuffaloCoder** [comment]
Created https://github.com/w0rp/ale/pull/213

**Comment by john-kurkowski** [comment]
Nice! Thank you! I gave it a whirl and it works as well as I remember Syntastic used to! (Syntastic being currently out of commission. See #91)

There is one other thing missing. It doesn't lint as I type. That's the main advantage of Ale. Instead, I have to save the file first. 

elm-make doesn't natively support compiling from stdin, but I think Ale has wrappers for that sort of thing.

**Comment by BuffaloCoder** [comment]
Ah, thanks for pointing that out! That should probably be updated. I'll work on that tonight.

**Comment by BuffaloCoder** [comment]
@john-kurkowski: the updates have been made to use stdin.  You should now see the lint occur as you type.

**Comment by BuffaloCoder** [comment]
This PR was merged, feel free to close this issue and post any further issues in the Ale project.

**Comment by john-kurkowski** [comment]
It works great. Thanks again!

**Comment by jschomay** [comment]
Trying it out, seems great.  I know the PR is closed, but I had two questions more related to Elm errors than Ale:

1.  Is there a way to get the ElmErrorDetail text?  I couldn't find out how to do so.
2. Errors in an imported file show up in the file that imports it.  Is there any way to fix that?

Other than that, awesome work, thank you for contributing this!

**Comment by BuffaloCoder** [comment]
@jschomay 

1. To my understanding, the current elm#ErrorDetail logic is tied to the results of the elm#Build process. The first step might be making that more generic, which you may want to make a separate issue for if you think that's the right process.
Even then It would still be hard to do in combination with the Ale linter. The linters are tied to the Ale project, and would require weird cross-project interaction.

2. You should add this issue to the ale project. I overlooked those errors when I implemented it.
