### ISSUE TITLE
Support for Elm 0.19

### ISSUE THREAD

**Issue by Right2Drive** [ElmCast/elm-vim#161]
As 0.19 was just released, was wondering what steps I need to take to get this plugin working properly. Thanks in advance! :smile:

**Comment by jschomay** [comment]
I'm wondering that too!  I just ran into it.  For the most part, everything just works.  After updating my global versions of elm and elm-format, the few issues that I have come across are:

- my ale linting doesn't understand how to deal with files in /test (it thinks everything should be in /src).  Not sure if that is an elm-vim problem, or an ale problem, but elm make and elm-test work fine.
- elm-oracle doesn't seem to work at all, though I'm not sure if this is due to elm 0.19 or some other bug

**Comment by Right2Drive** [comment]
Did you have to create aliases for the old commands to map to the new commands (ex: `elm-make` -> `elm make`)? This might alleviate some of the issues until everything is patched

**Comment by jschomay** [comment]
Hmm, I did not do that. But the more that I think about it, my main usage
is just ale linting and formatting, both of which didn't need any changes.

**Comment by Right2Drive** [comment]
Cool thanks! I appreciate knowing this will work to some degree before putting in the effort integrating it into my configuration!

**Comment by 1602** [comment]
It looks like json output format in elm 0.19 has been changed, here's example of new format being handled https://github.com/w0rp/ale/blob/master/ale_linters/elm/make.vim
